name: Release
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 6.0.x
      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}/nuget-6.0.x/${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}/nuget-6.0.x/
      - name: Install OpenSSL 1.1
        run: |
          wget https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
      - name: Install Dependencies
        run: dotnet restore
      - name: Build Package
        run: dotnet build --configuration Release --no-restore Percy
      - name: Create Package
        run: dotnet pack --configuration Release Percy
      - name: Publish Package
        run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_TOKEN -s $NUGET_SOURCE
        env:
          NUGET_SOURCE: https://api.nuget.org/v3/index.json
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
